plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      bulletproof-font-face:
        enabled: false
