version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      bulletproof-font-face:
        enabled: false
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  stylelint:
    enabled: true
