pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=codeclimate
      - status-success=now
      - status-success=security/snyk (proux)
    actions:
      merge:
        method: merge
